export const SET_FROM = 'SET_FROM'
export const SET_TO = 'SET_TO'
export const SIDE = 'SIDE'
export const CITYDATA = 'CITYDATA'
export const IS_LOADING_CITY = 'IS_LOADING_CITY'
export const SHOW_CITY_SELECTOR = 'SHOW_CITY_SELECTOR'
